baseurl: ''
url: 'http://0.0.0.0:4000/'
destination: docs
email: alvorpodcast@gmail.com
markdown: kramdown
sass:
  sass_dir: _style
  style: compressed
defaults:
  - scope:
      path: ''
      type: posts
    values:
      published: 'true'
prose:
  rooturl: _posts
  media: media
  siteurl: 'http://norskesportspodkaster.no'
  relativeLinks: 'http://norskesportspodkaster.no/links.jsonp'
  metadata:
    _posts/podcasts:
      - name: published
        field:
          element: hidden
          value: 'true'
      - name: category
        field:
          element: hidden
          value: podcast
      - name: title
        field:
          element: text
          label: Navn
          placeholder: Nå Er Det Alvor
          value: ''
      - name: spotify_link
        field:
          element: text
          label: Spotify Link
          placeholder: 'https://open.spotify.com/episode/xxxxx'
          value: ''
      - name: apple_podcast_link
        field:
          element: text
          label: Apple Podcasts Link
          placeholder: 'https://open.spotify.com/episode/xxxxx'
          value: ''
      - name: patreon_link
        field:
          element: text
          label: Patreon Link
          placeholder: 'https://www.patreon.com/nedaproject'
          value: ''
      - name: tags
        field:
          element: multiselect
          label: Idrett
          placeholder: Velg idrett
          options:
            - name: Langrenn
              value: langrenn
            - name: Løping
              value: løping
            - name: Klatring
              value: klatring
            - name: Friluftsliv
              value: friluftsliv
            - name: Fotball
              value: fotball
      - name: publisher
        field:
          element: text
          label: Utgiver
          placeholder: Schibsted
          value: ''
